# Site settings
title: IEEE International Conference on eScience
subtitle: Conference Series

baseurl: /about

markdown: kramdown
enable-mathjax: yes

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - README.md
  - LICENSE
